---
jobs:
- name: test-domains-broker
  plan:
  - get: broker-src
    trigger: true
  - get: general-task
  - task: run-tests
    image: general-task
    file: broker-src/ci/run-tests.yml

- name: deploy-development
  plan:
  - in_parallel:
    - get: broker-src
      passed: [test-domains-broker]
      trigger: true
    - get: pipeline-tasks
    - get: broker-release
      trigger: true
    - get: stemcell-jammy
      trigger: true
    - get: terraform-yaml
      resource: terraform-yaml-development
    - get: general-task
  - task: terraform-secrets
    image: general-task
    file: broker-src/ci/terraform-secrets.yml
  - put: development-deployment
    params:
      stemcells:
      - stemcell-jammy/*.tgz
      releases:
      - broker-release/*.tgz
      manifest: broker-src/bosh/manifest.yml
      vars_files:
      - terraform-secrets/terraform.yml
  on_failure:
    put: slack
    params: &slack-failure-params
      text: |
        :x: FAILED to deploy cf-domains-service-broker on ((cf-api-url-development))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-failure-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: deploy-staging
  plan:
  - in_parallel:
    - get: broker-src
      passed: [test-domains-broker]
      trigger: true
    - get: pipeline-tasks
    - get: broker-release
      trigger: true
    - get: stemcell-jammy
      trigger: true
    - get: terraform-yaml
      resource: terraform-yaml-staging
    - get: general-task
  - task: terraform-secrets
    image: general-task
    file: broker-src/ci/terraform-secrets.yml
  - put: staging-deployment
    params:
      stemcells:
      - stemcell-jammy/*.tgz
      releases:
      - broker-release/*.tgz
      manifest: broker-src/bosh/manifest.yml
      vars_files:
      - terraform-secrets/terraform.yml
  on_failure:
    put: slack
    params:
      <<: *slack-failure-params
      text: |
        :x: FAILED to deploy cf-domains-service-broker on ((cf-api-url-staging))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: deploy-production
  plan:
  - in_parallel:
    - get: broker-src
      passed: [deploy-staging]
      trigger: true
    - get: pipeline-tasks
    - get: broker-release
      passed: [deploy-staging]
      trigger: true
    - get: stemcell-jammy
      trigger: true
    - get: terraform-yaml
      resource: terraform-yaml-production
    - get: general-task
  - task: terraform-secrets
    image: general-task
    file: broker-src/ci/terraform-secrets.yml
  - put: production-deployment
    params:
      stemcells:
      - stemcell-jammy/*.tgz
      releases:
      - broker-release/*.tgz
      manifest: broker-src/bosh/manifest.yml
      vars_files:
      - terraform-secrets/terraform.yml
  on_failure:
    put: slack
    params:
      <<: *slack-failure-params
      text: |
        :x: FAILED to deploy cf-domains-service-broker on ((cf-api-url-production))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

resources:
- name: broker-src
  type: git
  source:
    uri: ((cf-domains-broker-git-url))
    branch: ((cf-domains-broker-git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: pipeline-tasks
  type: git
  source:
    uri: ((pipeline-tasks-git-url))
    branch: ((pipeline-tasks-git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: broker-release
  type: s3-iam
  source:
    bucket: ((bosh-releases-bucket))
    region_name: ((aws-region))
    regexp: domain-broker-(.*).tgz

- name: stemcell-jammy
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-jammy-go_agent

- name: terraform-yaml-development
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file-development))
    region_name: ((aws-region))

- name: terraform-yaml-staging
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file-staging))
    region_name: ((aws-region))

- name: development-deployment
  type: bosh-deployment
  source:
    target: ((bosh-target-development))
    client: ((bosh-client-development))
    client_secret: ((bosh-client-secret-development))
    ca_cert: ((ca-cert))
    deployment: domain-broker

- name: staging-deployment
  type: bosh-deployment
  source:
    target: ((bosh-target-staging))
    client: ((bosh-client-staging))
    client_secret: ((bosh-client-secret-staging))
    ca_cert: ((ca-cert))
    deployment: domain-broker

- name: production-deployment
  type: bosh-deployment
  source:
    target: ((bosh-target-production))
    client: ((bosh-client-production))
    client_secret: ((bosh-client-secret-production))
    ca_cert: ((ca-cert))
    deployment: domain-broker

- name: terraform-yaml-production
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file-production))
    region_name: ((aws-region))

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: general-task
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: general-task
    aws_region: us-gov-west-1
    tag: latest

resource_types:
- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest

- name: s3-iam
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: s3-resource
    aws_region: us-gov-west-1
    tag: latest

- name: bosh-deployment
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: bosh-deployment-resource
    aws_region: us-gov-west-1
    tag: latest

- name: slack-notification
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: slack-notification-resource
    aws_region: us-gov-west-1
    tag: latest

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest

- name: bosh-io-stemcell
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: bosh-io-stemcell-resource
    aws_region: us-gov-west-1
    tag: latest
